prefix dexpi: <https://rdf.equinor.com/dexpi#> 
prefix imf: <http://ns.imfid.org/imf#> 


SELECT * WHERE {
    ?eq1 rdfs:label "75SA21-80"
    ; (imf:connectedTo |^imf:connectedTo)* ?internal2.
# ?internal1 rdfs:label ?label1.
?internal2 rdfs:label ?label2.
}