version: '3'
services:
  rdfox: 
    image: oxfordsemantic/rdfox
    command: sandbox /home/rdfox/.RDFox/rdfox dexpi
    stdin_open: true
    tty: true
    ports:
      - 12110:12110
    volumes:
      - ${PWD}:/home/rdfox/.RDFox/
      - ${PWD}/RDFox.lic:/opt/RDFox/RDFox.lic
    depends_on:
      - rml-mapper
  rml-mapper:
    build: rml-mapper
    volumes:
      - ${PWD}:/app/local/
  web:
    build: web
    tty: true
    ports:
      - 8080:80
    volumes:
      - ${PWD}/www:/var/www/html/
    depends_on:
      - rml-mapper