version: '3'
services:
  rdfox: 
    image: oxfordsemantic/rdfox
    command: sandbox /home/rdfox/.RDFox/rdfox dexpi
    stdin_open: true
    tty: true
    ports:
      - 12110:12110
    volumes:
      - ${PWD}:/home/rdfox/.RDFox/
      - ${PWD}/RDFox.lic:/opt/RDFox/RDFox.lic
  rml-mapper:
    build: .
    tty: true
    ports:
      - 8080:80
    volumes:
      - ${PWD}:/app/local/
    depends_on:
      - rdfox
    