name: "Run tests (required)"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:  
  dotnet-tests:
    runs-on: ubuntu-latest
    name: ".NET Tests & Reports for symbol-translator"
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./SymbolLibrary/SymbolLibrary.sln

    - name: Copy NOAKADEXPI Symbol library
      run:  curl -o SymbolLibrary/src/Data/Symbols.xlsm https://github.com/equinor/NOAKADEXPI/raw/refs/heads/main/Symbols.xlsm

    - name: Build
      run: dotnet build ./SymbolLibrary/SymbolLibrary.sln --no-restore

    - name: Test
      run: |
        dotnet test ./SymbolLibrary/SymbolLibrary.sln --no-build --verbosity normal 
